apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameflow-ingress
spec:
  rules:
    - host: gameflow.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gameflow-api
                port:
                  number: 80
          - path: /hubs
            pathType: Prefix
            backend:
              service:
                name: gameflow-signalr
                port:
                  number: 80
